package org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler

import org.tabooproject.fluxon.runtime.FluxonRuntime
import org.tabooproject.fluxon.runtime.Type
import org.tabooproject.fluxon.runtime.FunctionSignature.returns
import org.tabooproject.fluxon.runtime.FunctionSignature.returnsVoid
import taboolib.common.LifeCycle
import taboolib.common.Requires
import taboolib.common.platform.Awake
import taboolib.common.platform.Platform
import taboolib.common.platform.PlatformSide

@Requires(classes = ["org.bukkit.scheduler.BukkitScheduler"])
@PlatformSide(Platform.BUKKIT)
object FnBukkitScheduler {

    val TYPE = Type.fromClass(org.bukkit.scheduler.BukkitScheduler::class.java)

    @Awake(LifeCycle.INIT)
    private fun init() {
        with(FluxonRuntime.getInstance()) {
            registerExtension(org.bukkit.scheduler.BukkitScheduler::class.java)
                .function("scheduleSyncDelayedTask", returns(Type.I).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java), Type.J)) { it.setReturnInt(it.target?.scheduleSyncDelayedTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable, it.getLong(2).toLong()) ?: 0) }
                .function("scheduleSyncDelayedTask", returns(Type.I).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitRunnable.TYPE, Type.J)) { it.setReturnInt(it.target?.scheduleSyncDelayedTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as org.bukkit.scheduler.BukkitRunnable, it.getLong(2).toLong()) ?: 0) }
                .function("scheduleSyncDelayedTask", returns(Type.I).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java))) { it.setReturnInt(it.target?.scheduleSyncDelayedTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable) ?: 0) }
                .function("scheduleSyncDelayedTask", returns(Type.I).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitRunnable.TYPE)) { it.setReturnInt(it.target?.scheduleSyncDelayedTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as org.bukkit.scheduler.BukkitRunnable) ?: 0) }
                .function("scheduleSyncRepeatingTask", returns(Type.I).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java), Type.J, Type.J)) { it.setReturnInt(it.target?.scheduleSyncRepeatingTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable, it.getLong(2).toLong(), it.getLong(3).toLong()) ?: 0) }
                .function("scheduleSyncRepeatingTask", returns(Type.I).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitRunnable.TYPE, Type.J, Type.J)) { it.setReturnInt(it.target?.scheduleSyncRepeatingTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as org.bukkit.scheduler.BukkitRunnable, it.getLong(2).toLong(), it.getLong(3).toLong()) ?: 0) }
                .function("scheduleAsyncDelayedTask", returns(Type.I).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java), Type.J)) { it.setReturnInt(it.target?.scheduleAsyncDelayedTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable, it.getLong(2).toLong()) ?: 0) }
                .function("scheduleAsyncDelayedTask", returns(Type.I).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java))) { it.setReturnInt(it.target?.scheduleAsyncDelayedTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable) ?: 0) }
                .function("scheduleAsyncRepeatingTask", returns(Type.I).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java), Type.J, Type.J)) { it.setReturnInt(it.target?.scheduleAsyncRepeatingTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable, it.getLong(2).toLong(), it.getLong(3).toLong()) ?: 0) }
                // .function("callSyncMethod", returns(Type.fromClass(java.util.concurrent.Future::class.java)).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.util.concurrent.Callable::class.java))) { it.setReturnRef(it.target?.callSyncMethod(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.util.concurrent.Callable)) }
                .function("cancelTask", returnsVoid().params(Type.I)) { it.target?.cancelTask(it.getInt(0).toInt()) }
                .function("cancelTasks", returnsVoid().params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE)) { it.target?.cancelTasks(it.getRef(0) as org.bukkit.plugin.Plugin) }
                .function("isCurrentlyRunning", returns(Type.Z).params(Type.I)) { it.setReturnBool(it.target?.isCurrentlyRunning(it.getInt(0).toInt()) ?: false) }
                .function("isQueued", returns(Type.Z).params(Type.I)) { it.setReturnBool(it.target?.isQueued(it.getInt(0).toInt()) ?: false) }
                .function("getActiveWorkers", returns(Type.LIST).noParams()) { it.setReturnRef(it.target?.getActiveWorkers()) }
                .function("getPendingTasks", returns(Type.LIST).noParams()) { it.setReturnRef(it.target?.getPendingTasks()) }
                .function("runTask", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java))) { it.setReturnRef(it.target?.runTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable)) }
                // .function("runTask", returnsVoid().params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.util.function.Consumer::class.java))) { it.target?.runTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.util.function.Consumer) }
                .function("runTask", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitRunnable.TYPE)) { it.setReturnRef(it.target?.runTask(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as org.bukkit.scheduler.BukkitRunnable)) }
                .function("runTaskAsynchronously", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java))) { it.setReturnRef(it.target?.runTaskAsynchronously(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable)) }
                // .function("runTaskAsynchronously", returnsVoid().params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.util.function.Consumer::class.java))) { it.target?.runTaskAsynchronously(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.util.function.Consumer) }
                .function("runTaskAsynchronously", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitRunnable.TYPE)) { it.setReturnRef(it.target?.runTaskAsynchronously(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as org.bukkit.scheduler.BukkitRunnable)) }
                .function("runTaskLater", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java), Type.J)) { it.setReturnRef(it.target?.runTaskLater(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable, it.getLong(2).toLong())) }
                // .function("runTaskLater", returnsVoid().params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.util.function.Consumer::class.java), Type.J)) { it.target?.runTaskLater(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.util.function.Consumer, it.getLong(2).toLong()) }
                .function("runTaskLater", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitRunnable.TYPE, Type.J)) { it.setReturnRef(it.target?.runTaskLater(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as org.bukkit.scheduler.BukkitRunnable, it.getLong(2).toLong())) }
                .function("runTaskLaterAsynchronously", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java), Type.J)) { it.setReturnRef(it.target?.runTaskLaterAsynchronously(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable, it.getLong(2).toLong())) }
                // .function("runTaskLaterAsynchronously", returnsVoid().params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.util.function.Consumer::class.java), Type.J)) { it.target?.runTaskLaterAsynchronously(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.util.function.Consumer, it.getLong(2).toLong()) }
                .function("runTaskLaterAsynchronously", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitRunnable.TYPE, Type.J)) { it.setReturnRef(it.target?.runTaskLaterAsynchronously(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as org.bukkit.scheduler.BukkitRunnable, it.getLong(2).toLong())) }
                .function("runTaskTimer", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java), Type.J, Type.J)) { it.setReturnRef(it.target?.runTaskTimer(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable, it.getLong(2).toLong(), it.getLong(3).toLong())) }
                // .function("runTaskTimer", returnsVoid().params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.util.function.Consumer::class.java), Type.J, Type.J)) { it.target?.runTaskTimer(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.util.function.Consumer, it.getLong(2).toLong(), it.getLong(3).toLong()) }
                .function("runTaskTimer", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitRunnable.TYPE, Type.J, Type.J)) { it.setReturnRef(it.target?.runTaskTimer(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as org.bukkit.scheduler.BukkitRunnable, it.getLong(2).toLong(), it.getLong(3).toLong())) }
                .function("runTaskTimerAsynchronously", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.lang.Runnable::class.java), Type.J, Type.J)) { it.setReturnRef(it.target?.runTaskTimerAsynchronously(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.lang.Runnable, it.getLong(2).toLong(), it.getLong(3).toLong())) }
                // .function("runTaskTimerAsynchronously", returnsVoid().params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, Type.fromClass(java.util.function.Consumer::class.java), Type.J, Type.J)) { it.target?.runTaskTimerAsynchronously(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as java.util.function.Consumer, it.getLong(2).toLong(), it.getLong(3).toLong()) }
                .function("runTaskTimerAsynchronously", returns(org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitTask.TYPE).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE, org.tabooproject.fluxon.platform.bukkit.function.bukkit.scheduler.FnBukkitRunnable.TYPE, Type.J, Type.J)) { it.setReturnRef(it.target?.runTaskTimerAsynchronously(it.getRef(0) as org.bukkit.plugin.Plugin, it.getRef(1) as org.bukkit.scheduler.BukkitRunnable, it.getLong(2).toLong(), it.getLong(3).toLong())) }
                // .function("getMainThreadExecutor", returns(Type.fromClass(java.util.concurrent.Executor::class.java)).params(org.tabooproject.fluxon.platform.bukkit.function.bukkit.plugin.FnPlugin.TYPE)) { it.setReturnRef(it.target?.getMainThreadExecutor(it.getRef(0) as org.bukkit.plugin.Plugin)) }
        }
    }
}
